
# Install and Configure keepalived

---


# - name: Install packages
#  apt: name={{ item }} state=present update_cache=yes
#  with_items:
#    - keepalived

- name: Put configuration file for keepalived
  template:
    src: keepalived.conf.j2
    dest: "/etc/keepalived/keepalived.conf"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
     - restart keepalived
  tags: config_keepalived

- name: Write takeover script for EIP
  template:
    src: eip_switch.sh.j2
    dest: "/etc/keepalived/eip_switch.sh"
    owner: "root"
    group: "root"
    mode: 0744
  notify:
     - restart keepalived
  tags: config_keepalived



- name: Configure Keepalived to start at boot
  service:
    name: keepalived
    enabled: yes
    state: started

