
---

# handlers for pgbouncer

- name: start pgbouncer
  service:
    name: pgbouncer
    state: started

- name: stop pgbouncer
  service:
    name: pgbouncer
    state: stopped

- name: restart pgbouncer
  service:
    name: pgbouncer
    state: restarted

- name: reload pgbouncer
  service:
    name: pgbouncer
    state: reloaded

- name: restart eth1
  command: bash -c "ifdown eth1 && ifup eth1"


# handlers for keepalived

- name: restart keepalived
  service:
    name: keepalived
    state: restarted